name = "remix-cloudflare-workers"
type = "javascript"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [ 
  { binding = "REMIX_JOKE", id = "e1076e1120f945d184898c67de69758a" },
  { binding = "REMIX_JOKE_USER" }
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format="service-worker"
